# Generated by Django 4.1.3 on 2023-05-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('favourite_framework', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('learning_mode', models.CharField(choices=[('Self Taught', 'Self Taught'), ('Boot Camp', 'Boot Camp'), ('College', 'College')], max_length=100)),
                ('number_of_Projects', models.IntegerField()),
                ('current_level', models.CharField(choices=[('Master', 'Master'), ('Expert', 'Expert'), ('Intermediate', 'Intermediate'), ('Junior', 'Junior'), ('Beginner', 'Beginner')], max_length=100)),
                ('commendations', models.CharField(choices=[('Star 1', 'Star 1'), ('Star 2', 'Star 2'), ('Star 3', 'Star 3'), ('Star 4', 'Star 4'), ('Star 5', 'Star 5'), ('Star 6', 'Star 6'), ('Star 7', 'Star 7')], max_length=100)),
            ],
        ),
    ]
